# Generated by Django 4.2.4 on 2023-08-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('lost', 'lost'), ('inprogress', 'inprogress'), ('contacted', 'contacted'), ('won', 'won')], default='new', max_length=25),
        ),
    ]
