# Generated by Django 4.2.4 on 2023-09-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_created_at_team_created_by_team_members'),
        ('lead', '0002_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='team.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('low', 'low'), ('medium', 'medium')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('lost', 'lost'), ('won', 'won'), ('new', 'new'), ('inprogress', 'inprogress'), ('contacted', 'contacted')], default='new', max_length=25),
        ),
    ]
