# Generated by Django 4.2.4 on 2023-09-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('high', 'high'), ('medium', 'medium')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('inprogress', 'inprogress'), ('contacted', 'contacted'), ('new', 'new')], default='new', max_length=25),
        ),
    ]
