# Generated by Django 4.2.4 on 2023-09-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inprogress', 'inprogress'), ('lost', 'lost'), ('contacted', 'contacted'), ('won', 'won'), ('new', 'new')], default='new', max_length=25),
        ),
    ]
