# Generated by Django 4.2.4 on 2023-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_alter_lead_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inprogress', 'inprogress'), ('contacted', 'contacted'), ('lost', 'lost'), ('won', 'won'), ('new', 'new')], default='new', max_length=25),
        ),
    ]
